### ISSUE TITLE
Missing topojson

### ISSUE THREAD

**Issue by henryjameslau** [ONSdigital/cdn.ons.gov.uk-assets#23]
@fryford Missing msoa-by-lad topojson for 
E06000057 (Northumberland)
E07000240 (St Albans) 
E7000241 (Welwyn Hatfield) 
E07000242 (East Hertfordshire)
E07000243 (Stevenage)
E08000037 (Gateshead)

**Comment by henryjameslau** [comment]
Missing lsoa-by-lad topojson for
E07000242 (East Hertfordshire)
E07000243 (Stevenage)
E08000037 (Gateshead)

**Comment by Crispioso** [comment]
I've only just noticed this but am I good to close it @henryjameslau since it's from a while ago and more related to added more content, rather than an issue with uploading to the CDN?

**Comment by henryjameslau** [comment]
Yep, happy to close.
